version: '3.4'

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=FalconWallet
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # постоянное хранилище

  falconwallet.api:
    image: ${DOCKER_REGISTRY-}falconwalletapi
    build:
      context: .
      dockerfile: src/FalconWallet.API/Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__WalletDbContextConnection=Host=db;Port=5432;Database=FalconWallet;Username=postgres;Password=${POSTGRES_PASSWORD}
